#!/bin/bash
function banlys
{
    local var_logfile=""
    local flag_android="n"
    local flag_make="n"
    local flag_syntax="n"
    local flag_others="n"
    local flag_python="n"
    local flag_shell='n'

    local flag_edit="n"

    if [[ "$#" = "0" ]]
    then
        echo "Default action"
    fi
    while [[ "$#" != 0 ]]
    do
        case $1 in
            -a|--all)
                flag_android="y"
                flag_make="y"
                flag_syntax="y"
                flag_shell="y"
                flag_others="y"
                flag_python="y"
                ;;
            -v|--vim)
                flag_edit=y
                # shift 1
                # eval vim $@
                # return 0
                ;;
            -f|--log-file)
                var_logfile="${2}"
                shift 1
                ;;
            -d|-debug)
                flag_android="y"
                flag_make="y"
                flag_syntax="y"
                flag_shell="y"
                flag_others="y"
                flag_python="y"
                var_logfile="${2}"
                shift 1
                ;;
            -h|--help)
                cli_helper -c "banlys" -cd "build/compil error analyzer "
                cli_helper -t "SYNOPSIS"
                cli_helper -d "banlys [Options] [Value]"
                cli_helper -t "Options"
                cli_helper -o "-a|--all" -d "enable all debug flag"
                # cli_helper -o "-v|--verbose" -d "Verbose print "
                cli_helper -o "-v|--vim" -d "dirrect vim log file "
                cli_helper -o "-d|--debug" -d "Specify log file, and enable all debug filter, indicate -a,-f"
                cli_helper -o "-f|--log-file" -d "Specify log file"
                cli_helper -o "-h|--help" -d "Print help function "
                return 0
                ;;
            *)
                var_logfile="$@"
                break
                ;;
        esac
        shift 1
    done

    if [ "${flag_edit}" = "y" ]
    then
        vim ${var_logfile}
        return 0
    fi

    if [ "${flag_android}" = "y" ]
    then
        echo "flag_android: ${flag_android}"
        echo "---- Android log analysis"
        # local total_line=$(wc -l ${var_logfile} | cut -d " " -f1 )
        # cat ${var_logfile} | grep -B ${total_line} "error.*generated" | tac | grep -B ${total_line} "generated.$" | tac | mark_build
        cat -n ${var_logfile} | grep "error.*generated\|^FAILED:" | mark_build
    fi
    if [ "${flag_make}" = "y" ]
    then
        echo "---- Make log analysis"
        cat -n ${var_logfile} | grep "make.*Error\|Makefile.*\*\*\*" | mark_build
    fi
    if [ "${flag_syntax}" = "y" ]
    then
        echo "---- Syntax log analysis"
        tmp_pattern="undefined reference"
        cat -n ${var_logfile} | grep "${tmp_pattern}" | mark "${tmp_pattern}"

        tmp_pattern="unknown type name"
        cat -n ${var_logfile} | grep "${tmp_pattern}" | mark "${tmp_pattern}"
    fi

    if [ "${flag_shell}" = "y" ]
    then
        echo "---- command missing "
        cat -n ${var_logfile} | grep "command not found" | mark "command not found"

        echo "---- file/dir/permission missing "
        tmp_pattern="Can not find directory"
        cat -n ${var_logfile} | grep "${tmp_pattern}" | mark "${tmp_pattern}"

        tmp_pattern="No such file or directory"
        cat -n ${var_logfile} | grep "${tmp_pattern}" | mark "${tmp_pattern}"

        tmp_pattern="No space left on device"
        cat -n ${var_logfile} | grep "${tmp_pattern}" | mark "${tmp_pattern}"

        tmp_pattern="Permission denied"
        cat -n ${var_logfile} | grep "${tmp_pattern}" | mark "${tmp_pattern}"

        echo "---- shell error "
        tmp_pattern="Argument list too long"
        cat -n ${var_logfile} | grep "${tmp_pattern}" | mark "${tmp_pattern}"
    fi

    if [ "${flag_python}" = "y" ]
    then
        echo "---- python error"
        tmp_pattern="Traceback (most recent call last):"
        cat -n ${var_logfile} | grep "${tmp_pattern}" | mark "${tmp_pattern}"

    fi

    if [ "${flag_others}" = "y" ]
    then
        echo "---- Others error"
        tmp_pattern="syntax error"
        cat -n ${var_logfile} | grep "${tmp_pattern}" | mark "${tmp_pattern}"

        tmp_pattern="\-\-help"
        cat -n ${var_logfile} | grep "${tmp_pattern}" | mark "${tmp_pattern}"
    fi
}
banlys $@
